name: Auto Update Sub
on:
  schedule:
    - cron: "*/5 * * * *"  # 注意引号
  workflow_dispatch: true   # 明确设置为 true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python fetch_and_upload.py
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sub.txt
          git commit -m "Auto update sub"
          git push
